version: 2
jobs:
  build:
    working_directory: ~/unboxed/unboxed.co
    parallelism: 1
    shell: /bin/bash --login
    docker:
      - image: circleci/ruby:2.3.7-node
    steps:
    - checkout
    - run: mkdir -p /tmp/circleci-artifacts /tmp/circleci-test-results
    - run: echo -e "export RAILS_ENV=test\nexport RACK_ENV=test" >> $BASH_ENV
    - run: 'bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
        # --jobs=4 --retry=3 '
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
          # This is a broad list of cache paths to include many possible development environments
          # You can probably delete some of these entries
          - vendor/bundle
          - ~/virtualenvs
          - ~/.m2
          - ~/.ivy2
          - ~/.bundle
          - ~/.go_workspace
          - ~/.gradle
          - ~/.cache/bower
    - run: echo 'There is no database'
    - run: bundle exec middleman build --verbose
    - run: bundle exec rspec --format=documentation
