version: 2
jobs:
  build:
    working_directory: ~/unboxed/unboxed.co
    docker:
      - image: circleci/ruby:2.3.7-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dep-{{ .Branch }}-
            - v1-dep-production-
            - v1-dep-
      - run:
          name: Set RAILS and RACK env
          command: echo -e "export RAILS_ENV=test\nexport RACK_ENV=test" >> $BASH_ENV
      - run:
          name: Bundle install
          command: 'bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3'
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
            - vendor/bundle
            - ~/.bundle
      - run:
          name: Compile middleman application
          command: bundle exec middleman build --verbose
      - run:
          name: Rspec tests
          command: bundle exec rspec --format=documentation
