backend:
  name: 'github'
  repo: 'unboxed/unboxed.co'
  branch: 'production'

media_folder: 'source/assets/images/uploads'
public_folder: '/assets/images/uploads'

collections:
  - name: 'blog_posts'
    label: 'Blog posts'
    folder: '/source/blog'
    label_singular: 'blog post'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    extension: 'html.markdown' # Middleman v4 requires .html.markdown
    format: 'frontmatter'
    filter: {
      field: 'weekly_roundup' # Exclude weekly roundup, subject to change [1]
    }
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'

      - label: 'Full names of author(s)'
        name: authors
        widget: list
        allow_add: true

      - label: 'tags (optional, remove irrelevant tags)'
        name: tags
        required: false
        widget: list
        default:
          - Agile
          - Culture
          - Design
          - Events
          - Innovation
          - Lean
          - Rails

      - label: 'Image URL (optional, shown on the blog listing page)'
        name: main_image
        required: false
        widget: string

      - label: 'Date'
        name: 'date'
        widget: 'datetime'

      - label: 'Published?'
        name: published
        widget: boolean
        default: true

      - label: 'Body (toggle to markdown)'
        name: 'body'
        widget: 'markdown'

  - name: 'product_stories'
    label: 'Product stories'
    folder: '/source/product-stories'
    label_singular: 'product story'
    create: true
    slug: '{{slug}}'
    extension: 'html.markdown' # Middleman v4 requires .html.markdown
    format: 'frontmatter'
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'

      - label: 'Description (shown on the product story listing page)'
        name: 'description'
        widget: 'string'

      - label: 'Image URL low res (shown on the product story listing page - 454 x 180 px)'
        name: main_image
        widget: string

      - label: 'Date'
        name: 'date'
        widget: 'datetime'

      - label: 'Published?'
        name: published
        widget: boolean
        default: true

      - label: "Header Image"
        name: "header"
        widget: "image"

      - label: 'Intro (heading and bullet point summary)'
        name: introduction
        widget: object
        fields:
          - {label: "Intro", name: intro, widget: markdown}
          - {label: "Image", name: image, widget: image}

      - label: 'Body (toggle to markdown)'
        name: 'body'
        widget: 'markdown'

      # - label: "In numbers"
      #   name: "in_numbers_1"
      #   widget: "string"
      #
      # - label: "Paragraph and photo"
      #   name: "paragraph_1"
      #   widget: object
      #   fields:
      #     - {label: "Paragraph", name: paragraph, widget: markdown}
      #     - {label: "Image", name: image, widget: image}
      #
      # - label: "Quote"
      #   name: "quote_1"
      #   widget: string
      #
      # - label: "Paragraph and photo"
      #   name: "paragraph_2"
      #   widget: object
      #   fields:
      #     - {label: "Paragraph", name: paragraph, widget: markdown}
      #     - {label: "Image", name: image, widget: image}
      #
      # - label: "Quote"
      #   name: "quote_2"
      #   widget: string
      #
      # - label: "Paragraph and photo"
      #   name: "paragraph_3"
      #   widget: object
      #   fields:
      #     - {label: "Paragraph", name: paragraph, widget: markdown}
      #     - {label: "Image", name: image, widget: image}
      #
      # - label: "In numbers"
      #   name: "in_numbers_2"
      #   widget: "string"
      #
      # - label: "Paragraph and photo"
      #   name: "paragraph_4"
      #   widget: object
      #   fields:
      #     - {label: "Paragraph", name: paragraph, widget: markdown}
      #     - {label: "Image", name: image, widget: image}
      #
      # - label: "Quote"
      #   name: "quote_3"
      #   widget: string
      #

  - name: 'news_articles'
    label: 'News articles'
    folder: '/source/news'
    label_singular: 'news article'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    extension: 'html.markdown' # Middleman v4 requires .html.markdown
    format: 'frontmatter'
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'

      - label: 'Date'
        name: 'date'
        widget: 'datetime'

      - label: 'Published?'
        name: published
        widget: boolean
        default: true

      - label: 'Body (toggle to markdown)'
        name: 'body'
        widget: 'markdown'

  - name: 'weekly_roundup'
    label: 'Weekly roundups'
    folder: '/source/blog'
    label_singular: 'weekly roundup'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    extension: 'html.markdown' # Middleman v4 requires .html.markdown
    format: 'frontmatter'
    filter: {
      field: 'weekly_roundup',
      value: true
    }
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
        default: 'Roundup: '

      - label: 'Full names of author(s)'
        name: authors
        widget: list
        allow_add: true
        default:
          - Elena Tanasoiu
          - Murray Steele
          - Neil van Beinum

      - label: 'tags (optional)'
        name: tags
        required: false
        widget: list
        default:
          - Culture

      - label: 'Date'
        name: 'date'
        widget: 'datetime'

      - label: 'Published?'
        name: published
        widget: boolean
        default: true

      - label: 'Body (toggle to markdown)'
        name: 'body'
        widget: 'markdown'

# [1]: https://github.com/netlify/netlify-cms/issues/1000
